# Shadowrocket: 2026-05-19 17:37:54
[General]
bypass-system = false
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true
dns-direct-system = true
dns-fallback-system = false
dns-direct-fallback-proxy = true
dns-server = https://cloudflare-dns.com/dns-query,https://dns.google/dns-query
fallback-dns-server = https://common.dot.dns.yandex.net/dns-query
hijack-dns = :53
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32
# tun-included-routes =
always-real-ip = localhost,*.local,captive.apple.com,*stun*,*turn*,*ice*,*rtc*,*voip*
icmp-auto-reply = false
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT
update-url = https://translated.turbopages.org/proxy_u/en-en.en./https/raw.githubusercontent.com/bb4dd/shadowrocket-b4d-cfgs/refs/heads/main/ru_whitelist.conf

[Rule]
# IP-трекеры напрямую
RULE-SET,https://translated.turbopages.org/proxy_u/en-en.en./https/raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/refs/heads/main/rules/domains_geo_detect.list,DIRECT

# Белые списки напрямую
RULE-SET,https://translated.turbopages.org/proxy_u/en-en.en./https/cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geoip/release/text/whitelist.txt,DIRECT,no-resolve
RULE-SET,https://translated.turbopages.org/proxy_u/en-en.en./https/raw.githubusercontent.com/hxehex/russia-mobile-internet-whitelist/refs/heads/main/whitelist.txt,DIRECT
# RULE-SET,https://github.com/hxehex/russia-mobile-internet-whitelist/blob/main/cidrwhitelist.txt,DIRECT

# RULE-SET,https://raw.githubusercontent.com/bb4dd/shadowrocket-b4d-cfgs/refs/heads/main/whitelist_domains.txt,DIRECT

# Всё остальное через прокси
FINAL,PROXY
